fix(openai): Fix missing TypedDict import in py37
Should prevent an error:

> ddtrace/internal/module.py:220: in _exec_module
>     self.loader.exec_module(module)
> ddtrace/internal/log_writer.py:4: in <module>
>     from typing import TypedDict
> E   ImportError: cannot import name 'TypedDict' from 'typing' (/root/.pyenv/versions/3.7.16/lib/python3.7/typing.py)

TypedDict was added to typing in Python 3.8