chore(ci): pin selenium chrome to 4.46 instead of latest (#19217)
## Description

We are getting such [failures](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/1881035850):
```
Running with gitlab-runner 18.0.5-7dd18d2e (7dd18d2e)
  on gitlab-runner-amd64-shared-5d89b777bb-rbgfd _xbvGsbV_, system ID: r_YdjzSWYyFzzs
  feature flags: FF_SCRIPT_SECTIONS:true
Preparing the "kubernetes" executor
00:01
Preparing environment
00:00
ERROR: Error cleaning up pod: resource name may not be empty
ERROR: Job failed (system failure): prepare environment: setting up build pod: pods "runner-xbvgsbv-project-358-concurrent-0-kutwp28r" is forbidden: ValidatingAdmissionPolicy 'image-tag-latest' with binding 'image-tag-latest' denied request: Containers cannot use the "latest" image tag (or omit a tag). Offending container(s): selenium-chrome in namespace gitlab-runner. For more information, see: https://datadoghq.atlassian.net/wiki/spaces/K8S/pages/6345523384/VAP+Policy+Exclusions#Understanding-a-Denial-Message. Check https://docs.gitlab.com/runner/shells/#shell-profile-loading for more information
```

## Testing

<!-- Describe your testing strategy or note what tests are included -->

## Risks

<!-- Note any risks associated with this change, or "None" if no risks -->

## Additional Notes

<!-- Any other information that would be helpful for reviewers -->


Co-authored-by: federico.mon <federico.mon@datadoghq.com>