chore(ci): bump riot version for 3.7 compatibility issues (#11085)
With the new release of virtualenv==20.27.0, we were seeing new failures
with build_base_venv[3.7] (GitLab) and build_base_venv (CircleCI) jobs
when running:
```
riot -P -v generate --python=$PYTHON_VERSION
...
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.riot/venv_py3717/lib/python3.7/site-packages/pip/_vendor/typing_extensions.py", line 1039
    def TypedDict(typename, fields=_marker, /, *, total=True, closed=False, **kwargs):
                                            ^
SyntaxError: invalid syntax
ERROR:riot.riot:Dev install failed, aborting!
```
We need to pin to virtualenv==20.26.6 to continue supporting python3.7

The upload-artifact and download-artifact bumps were required to unblock
the riot CI. It had been a while since the last update to riot, and
since then, v2 has been deprecated and v3 will be deprecated next month
(Nov 2024), so we are bumping to v4 via tag.

The above changes were implemented in riot
(https://github.com/DataDog/riot/pull/232), and this PR just bumps the
riot version in dd-trace-py from 0.19.1 to 0.20.0