(chore) Fix Flaky test_asyncio test
This change ensures that the MainThread Task with name 'None' is run
long enough to be targted by an event collector during this test.

Prior to this change the test
tests/profiling/collector/test_stack_asyncio.py::test_asyncio failed
occasionally due to a race condition between event collectors (which
scan threads) and collecting data about the MainThread with name=None.
If the collectors didn't run in time to catch the MainThread, no CPU
time would be recorded.

After this change, the StackCollector class has been updated to have a
'run count' variable, and sleeps are performed until the run time is
incremented at least once, thus guaranteeing a run (for both wall_clock
and cpu_time).

Sample error:

```
        assert wall_time_ns[t1_name] > 0
        assert wall_time_ns[t2_name] > 0
        if sys.platform != "win32":
            # Windows seems to get 0 CPU for this
>           assert cpu_time_found
E           assert False

tests/profiling/collector/test_stack_asyncio.py:90: AssertionError
```

Testing

This change was tested by increasing the collection interval
from 2*sys.setswitchinterval to 100*sys.setswitchinterval. These
settings guaranteed 0% test success prior to the fix and 100% test
success after, over 50 runs.