chore(iast): propagation error in replace aspect (#11120)
Fix a propagation error in the replace aspect detected in the log
explorer

```
File "/usr/local/lib/python3.12/site-packages/django/core/handlers/wsgi.py", line 67, in __init__
    self.path = "%s/%s" % (script_name.rstrip("/"), path_info.replace("/", "", 1))

File "/usr/local/lib/python3.12/site-packages/ddtrace/appsec/_iast/_taint_tracking/aspects.py", line 816, in replace_aspect
    iast_taint_log_error("replace_aspect. {}".format(e))

File "/usr/local/lib/python3.12/site-packages/ddtrace/appsec/_iast/_taint_tracking/__init__.py", line 129, in iast_taint_log_error
    _set_iast_error_metric("[IAST] Propagation error. %s" % msg)

File "/usr/local/lib/python3.12/site-packages/ddtrace/appsec/_deduplications.py", line 44, in __call__
    result = self.func(*args, **kwargs)

File "/usr/local/lib/python3.12/site-packages/ddtrace/appsec/_iast/_metrics.py", line 70, in _set_iast_error_metric
    res.extend(traceback.format_stack(limit=20))

File "/usr/local/lib/python3.12/site-packages/ddtrace/appsec/_iast/_taint_tracking/aspects.py", line 809, in replace_aspect
    aspect_result = aspect_replace_api(candidate_text, old_value, new_value, count, orig_result)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.12/site-packages/ddtrace/appsec/_iast/_taint_tracking/aspects.py", line 763, in aspect_replace_api
    result_formatted = as_formatted_evidence(new_value, tag_mapping_function=TagMappingMode.Mapper).join(new_elements)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found
```

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

(cherry picked from commit f5314ed0c18b7a663039356d098c77f259d636ac)