fix(wsgi): ensure traced iterable does not implement __len__ (#5858)
Streaming responses with [waitress](https://github.com/Pylons/waitress)
is not supported by the wsgi middleware. This incompatibility was
introduced by the following commit:
https://github.com/DataDog/dd-trace-py/commit/7ce49bd78b0d510766fc5db12756a8840724febc.

## Reproduction

1. `pip install "waitress>=2.1.2" "ddtrace==1.13.0"
"Flask>=2.2.4,<2.3.0"`
2. Create a flask application and add an endpoint that streams a
response:
   app.py:
    ```
    from waitress import serve
    from flask import Flask
    
    app = Flask(__name__)
    
    @app.route('/large.csv')
    def generate_large_csv():
        def generate():
            for row in [1, 2, 3, 4]:
                yield f"{row}\n"
        return app.response_class(generate(), mimetype='text/csv')
    
    @app.route("/")
    def hello():
        return "Hello, World!"

    serve(app, listen='*:8080')
    ```
3. Run ` python path/to/flask_app/app.py`
3. Run `curl http://localhost:8080/large.csv`
4. Error:
    ```
    ERROR:waitress:Exception while serving /large.csv
    Traceback (most recent call last):
File
"/s1/remote-venvs/tesla/lib/python3.10/site-packages/waitress/channel.py",
line 428, in service
        task.service()
File
"/s1/remote-venvs/tesla/lib/python3.10/site-packages/waitress/task.py",
line 168, in service
        self.execute()
File
"/s1/remote-venvs/tesla/lib/python3.10/site-packages/waitress/task.py",
line 466, in execute
        app_iter_len = len(app_iter)
    TypeError: object of type 'ClosingIterator' has no len()
    ```

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included
in the PR.
- [x] Risk is outlined (performance impact, potential for breakage,
maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines)
are followed.
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/)).
- [x] OPTIONAL: PR description includes explicit acknowledgement of the
performance implications of the change as reported in the benchmarks PR
comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment.

---------

Co-authored-by: Yun Kim <35776586+Yun-Kim@users.noreply.github.com>