ci: update testagent version and use vcr ci mode (#14651)
## Description

Updates the testagent version to 1.34.0, which added a CI mode for the
VCR proxy feature, which throws if a cassette is missing for a given
proxied request.

## Testing

I will include a commit that removes a cassette for one of our (LLM
Observability) tests, and will attach the output from CI here. Then, the
commit will be reverted.

```
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.riot/venv_py31018_14825e2ec901e2cc/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Cassette openai_completions_post_076bb2cf.yaml not found while running in CI mode. Please generate the cassette locally and commit it.
```

Additionally, I verified that running the container locally did just end
up re-generating the cassette.

## Risks

None

---------

Co-authored-by: Brett Langdon <brett.langdon@datadoghq.com>