docs: update pytest supported scope
The reported pytest scope claims anything above 3.0, however the API
used of `Node.iter_markers(name)` was only introduced in pytest 3.6.0

Running this on earlier versions of pytest will error with (abbreviated
stack):

    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/ddtrace/contrib/pytest/plugin.py", line 83, in pytest_runtest_protocol
    INTERNALERROR>     markers = [marker.kwargs for marker in item.iter_markers(name="dd_tags")]
    INTERNALERROR> AttributeError: 'Function' object has no attribute 'iter_markers

This might benefit from a test scope tightening.

Refs: https://docs.pytest.org/en/stable/changelog.html#pytest-3-6-0-2018-05-23

Signed-off-by: Mike Fiedler <miketheman@gmail.com>