fix(python 2.7): profiler raises a typing error when Span.resource is unicode (#3129) (#3148)
In python 2.7 the profiler fails to export http events if the resource name is unicode (commit which introduced typing in the profiler 6520212).

Sample Error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/scheduler.py", line 53, in flush
    exp.export(events, start, self._last_export)
  File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/exporter/http.py", line 150, in export
    profile = super(PprofHTTPExporter, self).export(events, start_time_ns, end_time_ns)
  File "ddtrace/profiling/exporter/pprof.pyx", line 594, in ddtrace.profiling.exporter.pprof.PprofExporter.export
  File "ddtrace/profiling/exporter/pprof.pyx", line 493, in ddtrace.profiling.exporter.pprof.PprofExporter._group_stack_events
  File "ddtrace/profiling/exporter/pprof.pyx", line 482, in ddtrace.profiling.exporter.pprof.PprofExporter._stack_event_group_key
  File "ddtrace/profiling/exporter/pprof.pyx", line 555, in ddtrace.profiling.exporter.pprof.PprofExporter._get_event_trace_resource
TypeError: Expected str, got unicode
```

Co-authored-by: Kyle Verhoog <kyle@verhoog.ca>
(cherry picked from commit 73d3c808a15c734c45ec0919c7f7f0b985439ab4)

Co-authored-by: Munir Abdinur <munir.abdinur@datadoghq.com>