fix(azure_functions): handle consuming a list of service bus messages (#14073)
When the
[cardinality](https://learn.microsoft.com/en-us/javascript/api/@azure/functions/servicebustopicfunctionoptions?view=azure-node-latest#@azure-functions-servicebustopicfunctionoptions-cardinality)
for an Azure Function is set to `many`, a list of messages is passed
instead of a single message, resulting in an exception with the current
instrumentation. This PR checks if a single message or list of messages
is passed to the function consuming service bus messages and extracts
the context appropriately depending on the type.

- Single message -> extract context from `application_properties`
- List of messages, all with same context -> extract context from
`application_properties` from first message
- List of messages, some with different contexts -> for now don't
extract context, right now a separate trace will be created for this
case. Will address in a future PR, potentially with span links.

In addition, the `messaging.message_id` span attribute will only be
added in the case of a single message being consumed, otherwise it is
omitted.

```
[2025-07-18T21:14:01.175Z] Exception: AttributeError: 'list' object has no attribute 'application_properties'
[2025-07-18T21:14:01.175Z] Stack:   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.7030/workers/python/3.11/OSX/Arm64/azure_functions_worker/dispatcher.py", line 671, in _handle__invocation_request
[2025-07-18T21:14:01.175Z]     call_result = await self._loop.run_in_executor(
[2025-07-18T21:14:01.175Z]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-18T21:14:01.175Z]   File "/Users/duncan.harvey/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
[2025-07-18T21:14:01.175Z]     result = self.fn(*self.args, **self.kwargs)
[2025-07-18T21:14:01.175Z]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-18T21:14:01.175Z]   File "/Users/duncan.harvey/go/src/github.com/DataDog/serverless-self-monitoring/self_monitor/azure/functions/src/python/.venv/lib/python3.11/site-packages/ddtrace/contrib/internal/futures/threading.py", line 42, in _wrap_execution
[2025-07-18T21:14:01.175Z]     return fn(*args, **kwargs)
[2025-07-18T21:14:01.175Z]            ^^^^^^^^^^^^^^^^^^^
[2025-07-18T21:14:01.175Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.7030/workers/python/3.11/OSX/Arm64/azure_functions_worker/dispatcher.py", line 1001, in _run_sync_func
[2025-07-18T21:14:01.175Z]     return ExtensionManager.get_sync_invocation_wrapper(context,
[2025-07-18T21:14:01.175Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-18T21:14:01.175Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.7030/workers/python/3.11/OSX/Arm64/azure_functions_worker/extension.py", line 211, in _raw_invocation_wrapper
[2025-07-18T21:14:01.175Z]     result = function(**args)
[2025-07-18T21:14:01.175Z]              ^^^^^^^^^^^^^^^^
[2025-07-18T21:14:01.175Z]   File "/Users/duncan.harvey/go/src/github.com/DataDog/serverless-self-monitoring/self_monitor/azure/functions/src/python/.venv/lib/python3.11/site-packages/ddtrace/contrib/internal/azure_functions/utils.py", line 49, in wrapper
[2025-07-18T21:14:01.175Z]     with context_factory(kwargs) as ctx, ctx.span:
[2025-07-18T21:14:01.175Z]          ^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-18T21:14:01.175Z]   File "/Users/duncan.harvey/go/src/github.com/DataDog/serverless-self-monitoring/self_monitor/azure/functions/src/python/.venv/lib/python3.11/site-packages/ddtrace/contrib/internal/azure_functions/patch.py", line 101, in context_factory
[2025-07-18T21:14:01.175Z]     "azure.functions.patched_service_bus", pin, resource_name, headers=msg.application_properties
```

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

---------

Co-authored-by: Munir Abdinur <munir.abdinur@datadoghq.com>