ci: do not use pip cache (#6541)
In an effort to reduce the occurance of the following error, this PR
proposes to remove the pip cache, at least temporarily to try and bisect
where the problem could be coming from.

> ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS
FILE.

Since the error only seems to occur in CircleCI, and is intermittent
running/re-running this PR's tests a few times might not be enough to
validate if this actually resolves the issue or not.


**Negative impact of this change:**

- We save/restore the pip cache for each job and node hashed on
`riotfile.py` and `setup.py`. This is meant to save us time and
bandwidth from downloading packages from pip every time they are
installed. With this cache removed we may see job runtimes to increase a
bit because more downloads need to happen. The CI run from this PR did
not increase very much/at all.

**Why might this be related to the issue we are trying to solve?**

- If any files get corrupted in the pip cache, then pip will not able to
validate their hashes (pip will compare against the remote file hashes
regardless of a local file being used or not).

**What do we do if this doesn't work?**

- We can revert this PR since it is unrelated to the problem
- We can enable PIP verbose logging for a period of time to help further
debug the root cause/source of the issue to try and reproduce.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included
in the PR.
- [x] Risk is outlined (performance impact, potential for breakage,
maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
are followed. If no release note is required, add label
`changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)