chore(waf): fix block_config compatibility (#15208)
Adds a `.get()` method to the `Block_config` class to restore
dictionary-like API compatibility broken by PR #15042, fixing Lambda
integration failures.

PR #15042 changed `Block_config` from a dictionary to a class,
introducing a breaking API change that caused Lambda integration to fail
with:

```
AttributeError: 'Block_config' object has no attribute 'get'
Traceback (most recent call last):
  File "./python/lib/python3.13/site-packages/datadog_lambda/wrapper.py", line 187, in __call__
  File "./python/lib/python3.13/site-packages/datadog_lambda/asm.py", line 220, in get_asm_blocked_response
AttributeError: 'Block_config' object has no attribute 'get'
```

Rollback this ST PR after the merge
https://github.com/DataDog/system-tests/commit/f87f4dd5c5d152007a1c022d8338c102c63f6ea1

APPSEC-59959