fix(ci): fix flaky data streams test (#6349)
This change updates the flaky test `test_data_streams_sns_to_sqs` to
mock `time.time()`.

This test relies on time buckets being created and asserted on. If the
time progress during the test causes the time bucket to increment, then
we will not have the single bucket that is expected by this test.


https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/40125/workflows/6e0b9c6a-2dfd-4629-a120-29af4c0e280b/jobs/2696774

```
======================================================================
FAIL: test_data_streams_sns_to_sqs (tests.contrib.botocore.test.BotocoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/.riot/venv_py3916_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis6451_moto[all]_botocore/lib/python3.9/site-packages/moto/core/models.py", line 124, in wrapper
    result = func(*args, **kwargs)
  File "/root/project/.riot/venv_py3916_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis6451_moto[all]_botocore/lib/python3.9/site-packages/moto/core/models.py", line 124, in wrapper
    result = func(*args, **kwargs)
  File "/root/project/tests/contrib/botocore/test.py", line 1119, in test_data_streams_sns_to_sqs
    assert len(buckets) == 1, "Expected 1 bucket but found {}".format(len(buckets))
AssertionError: Expected 1 bucket but found 2
```

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included
in the PR.
- [x] Risk is outlined (performance impact, potential for breakage,
maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
are followed. If no release note is required, add label
`changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)