ci: disable appsec_iast_propagation benchmarks [backport 4.0] (#15283)
Backport 52d499bb14991d5d9edaa1dae0db0956ef9d8a4d from #15279 to 4.0.

## Description

They are failing with:

> AttributeError: 'OverheadControl' object has no attribute
'release_request'

Which means we aren't getting benchmark results, and now the SLO check
will fail if the results for a given benchmark are missing.

## Testing

<!-- Describe your testing strategy or note what tests are included -->

## Risks

<!-- Note any risks associated with this change, or "None" if no risks
-->

## Additional Notes

<!-- Any other information that would be helpful for reviewers -->

Co-authored-by: Brett Langdon <brett.langdon@datadoghq.com>
Co-authored-by: Emmett Butler <723615+emmettbutler@users.noreply.github.com>