chore(tracing): fix typing and warning logs in some tests (#13848)
The code assumes DatadogSampler is present, but it may also be a
RateSampler (according to tests)


```
Exception ignored in forksafe hook <bound method Tracer._child_after_fork of <tests.utils.DummyTracer object at 0x7a9d6c0c4be0>>
Traceback (most recent call last):
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/forksafe.py", line 36, in run_hooks
    hook()
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/_trace/tracer.py", line 412, in _child_after_fork
    self._recreate(reset_buffer=True)
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/_trace/tracer.py", line 432, in _recreate
    self._span_aggregator.reset(
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/_trace/processor/__init__.py", line 527, in reset
    self.sampling_processor.sampler._agent_based_samplers,
AttributeError: 'RateSampler' object has no attribute '_agent_based_samplers'
```

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)