fix(langchain): avoid attribute error on cancelled agenerate requests (#13746)
Since we do a try..finally for setting tags in our langchain integration
there's the possibility that the `response` is `None`:


https://github.com/DataDog/dd-trace-py/blob/4b87ee8f2251e3cf22ea2a94c0fd51903a4275bd/ddtrace/contrib/internal/langchain/patch.py#L378-L379

which results in an `AttributeError`:

```
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/datadog/apm/library/python/ddtrace_pkgs/site-packages-ddtrace-py3.11-manylinux2014/ddtrace/llmobs/_integrations/base.py", line 98, in llmobs_set_tags
    self._llmobs_set_tags(span, args, kwargs, response, operation)
  File "/opt/datadog/apm/library/python/ddtrace_pkgs/site-packages-ddtrace-py3.11-manylinux2014/ddtrace/llmobs/_integrations/langchain.py", line 176, in _llmobs_set_tags
    self._llmobs_set_tags_from_chat_model(span, args, kwargs, response, is_workflow=is_workflow)
  File "/opt/datadog/apm/library/python/ddtrace_pkgs/site-packages-ddtrace-py3.11-manylinux2014/ddtrace/llmobs/_integrations/langchain.py", line 467, in _llmobs_set_tags_from_chat_model
    for message_set in chat_completions.generations:
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
AttributeError: 'NoneType' object has no attribute 'generations'
```

the fix is trivial, unfortunately I couldn't get a more realistic repro
so I settled for the emulating the bug with the method call directly.