fix(sampling): validate_sampling_decision giving log warns on supported mechanisms (#13554)
https://github.com/DataDog/dd-trace-py/issues/13516 


https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/961877338#L460
=========================== short test summary info
============================
FAILED
tests/integration/test_sampling.py::test_supported_sampling_mechanism -
AssertionError: DATA_JOBS_MONITORING returned {'_dd.propagation_error':
'decoding_error'}
assert {'_dd.propagation_error': 'decoding_error'} !=
{'_dd.propagation_error': 'decoding_error'}
====== 1 failed, 104 passed, 28 skipped, 6 xpassed, 14 warnings in
26.31s ======
Test failed with exit code 1

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

---------

Co-authored-by: Emmett Butler <723615+emmettbutler@users.noreply.github.com>