fix(openai): add support for py37
Should prevent an error:

> File "/usr/local/lib/python3.7/site-packages/ddtrace/contrib/openai/_logging.py", line 4, in <module>
> from typing import TypedDict
> ImportError: cannot import name 'TypedDict' from 'typing' (/usr/local/lib/python3.7/typing.py)

TypedDict was added to typing in Python 3.8