fix(rc): switch from type to typecode for mp reliability (#14531)
This switches the shared data for the remote configuration
PublisherSubscriberConnector to use a typecode instead of an explicit
type to take advantage of an internal mapping. This should be more
reliable across Python versions and fix an issue with Python3.13:

```
get_mp_context().Array(c_char, SHARED_MEMORY_SIZE, lock=False): TypeError: this type has no size
```

This change should be identical, and for more information, see the docs
here:

-
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Array
- https://docs.python.org/3/library/array.html#module-array
- https://docs.python.org/3/library/ctypes.html

Refs: DEBUG-4453

Relevant stacktrace:

```
    self.data = get_mp_context().Array(c_char, SHARED_MEMORY_SIZE, lock=False)
                ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/multiprocessing/context.py", line 141, in Array
    return Array(typecode_or_type, size_or_initializer, lock=lock,
                 ctx=self.get_context())
  File "/usr/local/lib/python3.13/multiprocessing/sharedctypes.py", line 88, in Array
    obj = RawArray(typecode_or_type, size_or_initializer)
  File "/usr/local/lib/python3.13/multiprocessing/sharedctypes.py", line 61, in RawArray
    obj = _new_value(type_)
  File "/usr/local/lib/python3.13/multiprocessing/sharedctypes.py", line 40, in _new_value
    size = ctypes.sizeof(type_)
TypeError: this type has no size
```