refactor(writer): handle agent responses in the tracer (#7699)
This prevents coupling the writer to the sampling implementations. The
logic is moved to the tracer, which is already coupled with the sampling
implementation.

This also centralizes mutation of the samplers to the tracing class.
This will simplify future updates (like dynamic configuration of
sampling).

This change was previously
[reverted](https://github.com/DataDog/dd-trace-py/pull/7333) due to a
regression in the sampling behaviour. The regression was due to a
missing callback (identified here:
https://github.com/DataDog/dd-trace-py/pull/6178/files#r1416553567). To
prevent this regression in the future a test case was added in
https://github.com/DataDog/dd-trace-py/pull/7805. I confirmed that the
test covers the regression by running it locally:

```
(.venv) ~/d/dd-trace-py ❮❮❮ AGENT_VERSION=testagent pytest tests/integration/test_priority_sampling.py -k test_agent_sample_rate
=========================================================================================== test session starts ===========================================================================================                                                                                                                                                                                  

tests/integration/test_priority_sampling.py FEFE                                                                                                                                                    [100%]

================================================================================================= ERRORS ==================================================================================================
____________________________________________________________________________ ERROR at teardown of test_agent_sample_rate_keep _____________________________________________________________________________
At request <Request GET /test/session/snapshot >:
   At snapshot (token='tests.integration.test_priority_sampling.test_agent_sample_rate_keep'):
       - Expected span:
       {'duration': 197000,
        'meta': {'_dd.p.dm': '-0',
                 '_dd.p.tid': '656a1a2a00000000',
                 'language': 'python',
                 'runtime-id': '701521214f1f4473abe1afca4813fbec'},...
       - Received span:
       {'duration': 206000,
        'meta': {'_dd.p.dm': '-0',
                 '_dd.p.tid': '656fd77d00000000',
                 'language': 'python',
                 'runtime-id': 'f2ca8706356f479da0861200855ff847'},...
     At trace 'test' (1 spans):
      At snapshot compare of span 'test' at position 1 in trace:
       - Expected span:
       {'duration': 59000,
        'meta': {'_dd.base_service': '',
                 '_dd.p.dm': '-1',
                 '_dd.p.tid': '656a1a2b00000000',
                 'language': 'python',
                 'runtime-id': '701521214f1f4473abe1afca4813fbec'},...
   
       - Received span:
       {'duration': 59000,
        'meta': {'_dd.base_service': '',
                 '_dd.p.dm': '-0',
                 '_dd.p.tid': '656fd78100000000',
                 'language': 'python',
                 'runtime-id': 'f2ca8706356f479da0861200855ff847'},...
meta mismatch on '_dd.p.dm': got '-0' which does not match expected '-1'.

================================================================================================ FAILURES =================================================================================================
_______________________________________________________________________________________ test_agent_sample_rate_keep _______________________________________________________________________________________

    @pytest.mark.skipif(AGENT_VERSION != "testagent", reason="Tests only compatible with a testagent")
    @pytest.mark.snapshot(agent_sample_rate_by_service={"service:test,env:": 0.9999})
    def test_agent_sample_rate_keep():
        """Ensure that the agent sample rate is respected when a trace is auto sampled."""
        from ddtrace import tracer
    
        # First trace won't actually have the sample rate applied since the response has not yet been received.
        with tracer.trace(""):
            pass
        # Force a flush to get the response back.
        tracer.flush()
    
        # Subsequent traces should have the rate applied.
        with tracer.trace("test", service="test") as span:
            pass
>       assert span.get_metric("_dd.agent_psr") == pytest.approx(0.9999)
E       assert None == 0.9999 ± 1.0e-06
E         comparison failed
E         Obtained: None
E         Expected: 0.9999 ± 1.0e-06

tests/integration/test_priority_sampling.py:129: AssertionError

FAILED tests/integration/test_priority_sampling.py::test_agent_sample_rate_keep - assert None == 0.9999 ± 1.0e-06
FAILED tests/integration/test_priority_sampling.py::test_agent_sample_rate_reject - assert None == 0.0001 ± 1.0e-10
ERROR tests/integration/test_priority_sampling.py::test_agent_sample_rate_keep
ERROR tests/integration/test_priority_sampling.py::test_agent_sample_rate_reject
================================================================================= 2 failed, 2 warnings, 2 errors in 7.03s =================================================================================
```