fix(openai): fix handling streamed reasoning responses and tool message inputs for responses api (#14030)
This PR fixes two issues I noticed while writing some shared tests for
our OpenAI responses support:

1. When running a streamed reasoning inference using the responses API,
it is possible for our code to throw.

```bash
Error processing streamed completion/chat response.
Traceback (most recent call last):
  File "/Users/sam.brenner/dd/dd-trace-py/ddtrace/contrib/internal/openai/utils.py", line 306, in _process_finished_stream
    _set_token_metrics_from_streamed_response(span, formatted_completions, prompts, request_messages, kwargs)
  File "/Users/sam.brenner/dd/dd-trace-py/ddtrace/contrib/internal/openai/utils.py", line 356, in _set_token_metrics_from_streamed_response
    estimated, completion_tokens = _compute_completion_tokens(response, model_name)
  File "/Users/sam.brenner/dd/dd-trace-py/ddtrace/contrib/internal/openai/utils.py", line 391, in _compute_completion_tokens
    content = choice.get("content", "") or choice.get("text", "")
AttributeError: 'str' object has no attribute 'get'
Error generating LLMObs span event for span <Span(id=13583410398100141511,trace_id=138861942850127515599735367478775631197,parent_id=None,name=openai.request)>, likely due to malformed span
Traceback (most recent call last):
  File "/Users/sam.brenner/dd/dd-trace-py/ddtrace/llmobs/_llmobs.py", line 225, in _submit_llmobs_span
    span_event = self._llmobs_span_event(span)
  File "/Users/sam.brenner/dd/dd-trace-py/ddtrace/llmobs/_llmobs.py", line 241, in _llmobs_span_event
    raise KeyError("Span kind not found in span context")
KeyError: 'Span kind not found in span context'
```

This error was because it seems that it's possible for the `response`
from `streamed_chunks[0][0]` for the responses API to be a dict
representation of an openai `Response` object instead of the object
directly. Replacing `getattr` calls with our dict-object coalescing
`_get_attr` seems to do the trick and does not fail previous tests.

2. We were not properly stringifying tool content for LLM input messages
for tool message types.

The two tests added reflect these changes.

MLOB-3332

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

---------

Co-authored-by: lievan <42917263+lievan@users.noreply.github.com>