core: clean-up a couple debug logs (#1631)
The debug logs of the tracer have some noisy, not very helpful logs which can be cleaned up.

- `AttributeError: module 'ddtrace.contrib.boto' has no attribute 'patch'` often causes users to believe there is something broken or misconfigured with boto, when in reality this is expected behaviour for when boto is not installed.

- `Failed to parse cgroup file for pid 'self'` also looks like an error when in reality it is expected behaviour when running outside of a container.

* monkey: don't log on every module not installed occurrence

* runtime: don't log if cgroup file not found

* more accurate error handling

* more explicit error checking for container info