fix(profiling): dont link with libatomic [backport 3.19] (#15872)
## Description

On `python:3.13-slim` image using `ddtrace==3.19.3`, the latest patch
release in 3.19 line

```
>>> from ddtrace.profiling.collector import _memalloc
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from ddtrace.profiling.collector import _memalloc
  File "/usr/local/lib/python3.13/site-packages/ddtrace/internal/module.py", line 252, in _create_module
    return self.loader.create_module(spec)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
ImportError: libatomic.so.1: cannot open shared object file: No such file or directory
```

Using pre-built wheels from this branch, we no longer get above error
https://github.com/DataDog/dd-trace-py/actions/runs/20758839346?pr=15872

Example profiles obtained using pre-built wheel using
`python:3.13-slim-bookworm` image and dd-trace-doe
https://github.com/DataDog/dd-trace-doe/pull/227

https://app.datadoghq.com/profiling/explorer?query=doe.hash%3A04c50ba82218deef61d31581102d6420&agg_m=%40prof_python_cpu_cores&agg_m_source=base&agg_t=sum&extra_search_fields=%7B%22filters_query%22%3A%22%22%2C%22sample_type%22%3A%22cpu-time%22%7D&fromUser=true&my_code=disabled&profile_type=alloc-size&refresh_mode=paused&viz=flame_graph&from_ts=1767675600000&to_ts=1767727529056&live=false



## Testing

<!-- Describe your testing strategy or note what tests are included -->

## Risks

<!-- Note any risks associated with this change, or "None" if no risks
-->

## Additional Notes

<!-- Any other information that would be helpful for reviewers -->