fix(benchmark): tracer error, add otel_span to scenarios list (#5572)
Fix Benchmark CI:
- Tracer scenario error:
https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/256011926
```
Traceback (most recent call last):
  File "/app/candidate/benchmarks/scenario.py", line 3, in <module>
    from ..bm import utils
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/app/candidate/benchmarks/scenario.py", line 3, in <module>
    from ..bm import utils
ImportError: attempted relative import with no known parent package
```
- Add Otel_span scenario to `.gitlab/benchmarks.yml` list: 

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included
in the PR.
- [x] Risk is outlined (performance impact, potential for breakage,
maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines)
are followed.
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/)).
- [x] PR description includes explicit acknowledgement/acceptance of the
performance implications of this PR as reported in the benchmarks PR
comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment.