fix(llmobs): [MLOB-3863] openai agents support reasoning messages (#14522)
While QA-ing our agentic integrations, I noticed a bug in the current
Open AI Agent's output message parsing. The content field on OpenAI's
`ResponseReasoningItem` is optional
([ref](https://github.com/openai/openai-python/blob/2adf11112988e998fcf5adb805bae38501d22318/src/openai/types/responses/response_reasoning_item.py#L27-L51))
which we were not handling properly leading to potential `NoneType`
errors like the one below:

```
  File "/Users/nicole.cybul/go/src/github.com/DataDog/dd-trace-py/ddtrace/llmobs/_integrations/utils.py", line 1161, in llmobs_output_messages
    for content in item.content:
                   ^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

While investigating this issue, I noticed that our OpenAI integration
had a nearly identical implementation for parsing input and output
messages, so I decided to extract the common logic into a helper
function that could be reused across the OpenAI and OpenAI Agents
integrations. This fixed the `NoneType` error since now we do not try to
iterate over `item.content` for reasoning message types.

## Manual Testing
Here is a
[trace](https://app.datadoghq.com/llm/traces?query=%40ml_app%3Anicole-test%20%40event_type%3Aspan%20%40parent_id%3Aundefined&agg_m=count&agg_m_source=base&agg_t=count&fromUser=false&sp=%5B%7B%22sp%22%3A%7B%22width%22%3A%22min%28100%25%2C%20max%28calc%28100%25%20-%20var%28--ui-page-left-offset%29%20-%2016px%29%2C%20900px%29%29%22%7D%2C%22p%22%3A%7B%22eventId%22%3A%22AwAAAZkvInhdwYmtigAAABhBWmt2SW5oZEFBRExtZktfRkZzZEFBQUEAAAAkMDE5OTJmMjMtOTQxOC00OTliLTg1ZWYtYjc5ZjBmNGU5YjkzAABCrQ%22%7D%2C%22i%22%3A%22llm-obs-panel%22%7D%5D&spanId=9743349247239047563&start=1757431678372&end=1757432578372&paused=false)
that I created with this feature branch which can be compared with this
[trace](https://app.datadoghq.com/llm/traces?query=%40ml_app%3Anicole-test%20%40event_type%3Aspan%20%40parent_id%3Aundefined&agg_m=count&agg_m_source=base&agg_t=count&fromUser=true&sp=%5B%7B%22sp%22%3A%7B%22width%22%3A%22min%28100%25%2C%20max%28calc%28100%25%20-%20var%28--ui-page-left-offset%29%20-%2016px%29%2C%20900px%29%29%22%7D%2C%22p%22%3A%7B%22eventId%22%3A%22AwAAAZkvJpU3H4D3EQAAABhBWmt2SnBVM0FBQlh3NUdHTDY2SEFBQUEAAAAkZjE5OTJmMjYtY2MyMy00YTQxLThlZWQtZWJlNmZlNWYyOTE4AAAI6g%22%7D%2C%22i%22%3A%22llm-obs-panel%22%7D%5D&spanId=10719453409381675278&start=1757431833983&end=1757432733983&paused=false)
from the main branch.

|  | Before | After |
|---|---|---|
| OpenAI Agents LLM spans were missing output messages due to the
`NoneType` error). | <img width="1056" height="992" alt="image"
src="https://github.com/user-attachments/assets/3e94b71f-6d39-4044-af4d-bba901e3f850"
/> | <img width="1236" height="994" alt="image"
src="https://github.com/user-attachments/assets/266b4085-14d4-487e-946d-a5ea0af990f6"
/> |
| Tool Results for OpenAI Agents LLM spans were not being captured |
<img width="542" height="116" alt="image"
src="https://github.com/user-attachments/assets/8829ae88-add1-415c-964e-c2253478a595"
/> | <img width="1206" height="104" alt="image"
src="https://github.com/user-attachments/assets/26e829ff-efc8-4228-a289-1c1f316411f9"
/> |
| Spans were not being linked properly due to missing output messages |
<img width="1690" height="864" alt="image"
src="https://github.com/user-attachments/assets/b7c290a1-7474-4b7a-8cab-fca1e75732f5"
/> | <img width="548" height="1104" alt="image"
src="https://github.com/user-attachments/assets/b5542829-784d-4780-b33c-3a9843753bcb"
/> |


## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)