chore(tracer/writer): improve writing exception (#4692)
The current exception prints out a loud stack trace that contains a lot
of unhelpful information for both the developers and users of the
library.

```
ERROR:ddtrace.internal.writer:failed to send traces to Datadog Agent at http://localhost:8126/v0.5/traces
Traceback (most recent call last):
  File "/Users/kverhoog/dev/dd-trace-py/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "/Users/kverhoog/dev/dd-trace-py/ddtrace/internal/writer.py", line 447, in _send_payload
    response = self._put(payload, headers)
  File "/Users/kverhoog/dev/dd-trace-py/ddtrace/internal/writer.py", line 399, in _put
    self._conn.request("PUT", self._endpoint, data, headers)
  File "/Users/kverhoog/.pyenv/versions/3.10.3/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/kverhoog/.pyenv/versions/3.10.3/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/kverhoog/.pyenv/versions/3.10.3/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/kverhoog/.pyenv/versions/3.10.3/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Users/kverhoog/.pyenv/versions/3.10.3/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Users/kverhoog/.pyenv/versions/3.10.3/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/Users/kverhoog/.pyenv/versions/3.10.3/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/Users/kverhoog/.pyenv/versions/3.10.3/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kverhoog/dev/dd-trace-py/ddtrace/internal/writer.py", line 564, in flush_queue
    self._retry_upload(self._send_payload, encoded, n_traces)
  File "/Users/kverhoog/dev/dd-trace-py/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/kverhoog/dev/dd-trace-py/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 363, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x107799210 state=finished raised ConnectionRefusedError>]
```

Instead, the useful information can be included in the exception and the
stack trace can be omitted.

```
ERROR:ddtrace.internal.writer:failed to send 1 traces to Datadog Agent at http://localhost:8126/v0.5/traces after 3 retries ([Errno 61] Connection refused)
```

Co-authored-by: Brett Langdon <brett.langdon@datadoghq.com>
Co-authored-by: Munir Abdinur <munir.abdinur@datadoghq.com>