chore(llmobs): [MLOB-2093] remove deprecated parameters arg from annotate method (#12085)
Deprecates the `parameters` arg for the LLMObs annotation method in
favor of `metadata`.

I verified this change by running the following code:
```
@workflow
def run():
    LLMObs.annotate(
        input_data="hello",
        output_data="bye",
        parameters={"example": True},
    )
    return None

run()
```


Which produced the following error as expected: `TypeError:
LLMObs.annotate() got an unexpected keyword argument 'parameters'`.

Replacing `parameters` with `metadata` resolves the issue:


![image](https://github.com/user-attachments/assets/c6858362-43d6-4647-99a9-db4356cab539)


## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

---------

Co-authored-by: Yun Kim <35776586+Yun-Kim@users.noreply.github.com>