ci: update cython-lint and address errors (#15407)
## Description

`cython-lint` used to skip `_encoding.pyx` for 
```
cmd [5] | cython-lint .
Skipping file /Users/taegyun.kim/go/src/github.com/DataDog/dd-trace-py/ddtrace/internal/_encoding.pyx, as it cannot be parsed. Error: AttributeError("'_thread._local' object has no attribute 'cython_errors_listing_file'")
```

Updated `_encoding.pyx` as

```
/Users/taegyun.kim/go/src/github.com/DataDog/dd-trace-py/ddtrace/internal/_encoding.pyx:24:24: 'MAX_UINT_64BITS' imported but unused
/Users/taegyun.kim/go/src/github.com/DataDog/dd-trace-py/ddtrace/internal/_encoding.pyx:1237:19: 'longval' defined but unused (try prefixing with underscore?)
```


## Testing

<!-- Describe your testing strategy or note what tests are included -->

## Risks

<!-- Note any risks associated with this change, or "None" if no risks
-->

## Additional Notes

<!-- Any other information that would be helpful for reviewers -->