refactor(internal): don't release `sys.monitoring` tool if finalising (#20856)
## Description

https://datadoghq.atlassian.net/browse/PROF-16140

This PR updates the `monitoring` module to not release the `sys.monitoring` tool if the interpreter is finalising.

The problem was that registered Code Objects can be freed after interpreter has started shutting down and set the `monitoring` module's globals to `None`, in which case the `with _registry_lock` would fail. 

This was [detected in CI](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/2113786029) when I made changes that installed certain profiler hooks at startup (but the problem does not come from my changes, it's a design flaw of how the callback works, which is why I'm fixing it here).

```
FAILED tests/contrib/django/test_django_patch.py::test_instrument_templates_patching[py3.15] - AssertionError: STDERR: Expected [''] got:

Exception ignored while calling weakref callback <function _IdentityWeakKeyDictionary._make_remove.<locals>.remove at 0x705a2eaa35e0>:
Traceback (most recent call last):
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.cache/test-environments/1f807ff/lib/python3.15/site-packages/ddtrace/internal/monitoring.py", line 93, in remove
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.cache/test-environments/1f807ff/lib/python3.15/site-packages/ddtrace/internal/monitoring.py", line 151, in _on_code_registration_collected
TypeError: 'NoneType' object does not support the context manager protocol (missed __exit__ method)
```

**Note** Not adding a release note because this is only happening in 3.15+, which `ddtrace` doesn't support yet, so it's not really a bug fix.

Co-authored-by: thomas.kowalski <thomas.kowalski@datadoghq.com>