chore(llmobs): use upload endpoint for CSV's and large pushes (#14473)
**case 1: create dataset from CSVs**
with big datasets / big CSVs, we will run into timeout errors 

```
Traceback (most recent call last):
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/test.py", line 23, in <module>
    dataset = LLMObs.create_dataset_from_csv(csv_path="/Users/gary.huang/Downloads/weatherAUS.csv", dataset_name="weatheraus-2", input_data_columns=["Date", "input", "Evaporation", "Sunshine"], expected_output_columns=["RainTomorrow"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_llmobs.py", line 722, in create_dataset_from_csv
    ds.push()
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_experiment.py", line 140, in push
    new_version, new_record_ids = self._dne_client.dataset_batch_update(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_writer.py", line 404, in dataset_batch_update
    resp = self.request("POST", path, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_writer.py", line 319, in request
    resp = conn.getresponse()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out
```

now it succeeds

https://dddev.datadoghq.com/llm/datasets/1e794d07-8b77-4a08-8363-e7236432f262

**case 2: large push after dataset is created**
in cases where a push is extremely big, it used to fail before 
for example with this snippet
```
dataset = LLMObs.create_dataset("1-then-big-gh-09021126", "", [{"input_data": "first", "expected_output": "1"}])

print(dataset.as_dataframe())

print(dataset.url)

for i in range(0, 25000):
    dataset.append({"input_data": "a"*5000, "expected_output": "b"*100})

dataset.push()
```
results in something like
```
3.13.0rc1
  input_data expected_output
                            
0      first               1
https://app.datadoghq.com/llm/datasets/f9a2b6a7-9690-4e3d-98ff-e11b7832c344
Traceback (most recent call last):
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/test.py", line 33, in <module>
    dataset.push()
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_experiment.py", line 140, in push
    new_version, new_record_ids = self._dne_client.dataset_batch_update(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_writer.py", line 404, in dataset_batch_update
    resp = self.request("POST", path, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_writer.py", line 318, in request
    conn.request(method, url, encoded_body, headers)
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/internal/http.py", line 37, in request
    return super().request(method, url, body=body, headers=_headers, encode_chunked=encode_chunked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1130, in _send_output
    self.send(chunk)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1055, in send
    self.sock.sendall(data)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/ssl.py", line 1210, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/ssl.py", line 1179, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The write operation timed out
```
but with this change this succeeds by estimating the size of the dataset
to upload and using the bulk endpoint if the dataset gets large enough

https://dddev.datadoghq.com/llm/datasets/f9a2b6a7-9690-4e3d-98ff-e11b7832c344

**case 3: create dataset with a large list of records**
```
3.13.0rc1
Traceback (most recent call last):
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/test.py", line 27, in <module>
    dataset = LLMObs.create_dataset("1-then-big-gh-09021127", "", recs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_llmobs.py", line 657, in create_dataset
    ds.push()
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_experiment.py", line 140, in push
    new_version, new_record_ids = self._dne_client.dataset_batch_update(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_writer.py", line 404, in dataset_batch_update
    resp = self.request("POST", path, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/llmobs/_writer.py", line 318, in request
    conn.request(method, url, encoded_body, headers)
  File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/.venv/lib/python3.12/site-packages/ddtrace/internal/http.py", line 37, in request
    return super().request(method, url, body=body, headers=_headers, encode_chunked=encode_chunked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1130, in _send_output
    self.send(chunk)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/http/client.py", line 1055, in send
    self.sock.sendall(data)
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/ssl.py", line 1210, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary.huang/.pyenv/versions/3.12.7/lib/python3.12/ssl.py", line 1179, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The write operation timed out
```
it now succeeds

https://dddev.datadoghq.com/llm/datasets/4b4af632-a51b-4a18-9393-f0a5dfe8a2b5

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

---------

Co-authored-by: Yun Kim <35776586+Yun-Kim@users.noreply.github.com>