chore(profiling): fix fuzz link errors (#19719)
## Description

The `fuzzer_infra` CI job failed to link all `stack` fuzz targets -- this PR fixes it.

```
undefined reference to `Datadog::OriginTaskLinks::get_origin_task(unsigned long)'
undefined reference to `Datadog::OriginTaskLinks::enable()'
undefined reference to `Datadog::OriginTaskLinks::postfork_child()'
```

Root cause was #19082  introducing a new file but not linking it for fuzzing.

Co-authored-by: thomas.kowalski <thomas.kowalski@datadoghq.com>