fix(azure_functions): instrument azure functions regardless of decorator order (#13592)
Refactor Azure Functions instrumentation to patch the
`FunctionApp.get_functions` method instead of the individual decorators
for each trigger.

## Additional Notes

When the `function_name` decorator is first the function Datadog
instrumentation succeeds.
```
@app.function_name(name="customname")
@app.route(route="httpexample", auth_level=func.AuthLevel.ANONYMOUS)
def http_example(req: func.HttpRequest) -> func.HttpResponse:
    return func.HttpResponse("Hello Datadog!")
```

However if the `function_name` decorator is second, which is valid for
an uninstrumented function, Datadog instrumentation fails with the error
below.
```
@app.route(route="httpexample", auth_level=func.AuthLevel.ANONYMOUS)
@app.function_name(name="customname")
def http_example(req: func.HttpRequest) -> func.HttpResponse:
    return func.HttpResponse("Hello Datadog!")
```

```
[2025-06-04T15:47:21.117Z] Worker failed to index functions
[2025-06-04T15:47:21.118Z] Result: Failure
[2025-06-04T15:47:21.118Z] Exception: AttributeError: 'FunctionBuilder' object has no attribute '__name__'
```

This error happens because the decorators are patched one at a time in
order, and if the `function_name` decorator is patched after the `route`
decorator, then the patch method for `route` is missing information it
expected from the `function_name` decorator.

By patching
[get_functions](https://github.com/Azure/azure-functions-python-library/blob/03dc59a10d6116e36c5255d3d3649db2d525a472/azure/functions/decorators/function_app.py#L3902)
instead, we can access all functions right before they are loaded by the
[Python Azure Functions
Worker](https://github.com/Azure/azure-functions-python-worker/blob/9b17af96794307f4d34fc3ce8a6193aab9d7299f/azure_functions_worker/loader.py#L264)
and wrap the user defined methods to create spans.

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)