fix(llmobs): llmobs can be re-enabled on fork with agentless enabled [backport 3.2] (#12909)
Backport 269b3d8b37d1d42222f31452dc4580bb0a491b99 from #12889 to 3.2.

Due to a regression in
https://github.com/DataDog/dd-trace-py/pull/11961, agentless writers
fail to init in LLMObs on fork, as the `agentless_url` is not passed
down in `recreate`, resulting in:

```
File "/app/.venv/lib/python3.11/site-packages/ddtrace/llmobs/_writer.py", line 255, in __init__ 	
	raise ValueError("agentless_url is required for agentless mode")
	
ValueError: agentless_url is required for agentless mode
```

The fix is passing the value down appropriately.

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

Co-authored-by: Sam Brenner <106700075+sabrenner@users.noreply.github.com>