chore(ci_visibility): add Auto Test Retries to pytest plugin v2 (#11241)
Introduces support for Auto Test Retries to the v2 `pytest` plugin.

This retries tests that have failed their first attempt (except for
tests that have failed setup or teardown, which are not retried at all).
Failed tests that pass retries result in the session passing (with
`pytest` exiting with code 0). Test that fail all retries cause the
session to fail (exiting with code 1).

If any tests were retried, a section is added to the final summary
report, showing the results:
```
======================= Datadog Auto Test Retries ========================
_________________________________ FAILED _________________________________
FAILED tests/test_some_fail.py::test_func_fails_all_retries
_________________________________ PASSED _________________________________
PASSED tests/test_all_pass.py::TestAllPass::test_method_succeeds_on_5th_retry
PASSED tests/test_all_pass.py::TestAllPass::test_method_succeeds_on_1st_retry
PASSED tests/test_all_pass.py::test_func_succeeds_on_3rd
PASSED tests/test_all_pass.py::test_func_succeeds_first_retry
PASSED tests/test_some_fail.py::TestAllPass::test_method_succeeds_on_5th_retry
PASSED tests/test_some_fail.py::TestAllPass::test_method_succeeds_on_1st_retry
PASSED tests/test_some_fail.py::test_func_succeeds_on_3rd
PASSED tests/test_some_fail.py::test_func_succeeds_first_retry
___________________ Datadog Auto Test Retries summary ____________________
         1 failed, 8 passed (total attempts: 26 failed, 8 passed)
==========================================================================
```

Other changes in this PR:
- Some refactoring to DRY `pytest` retry logic 
- Introduction of API to "stash" data on Test Visibility objects 
- Tweak to ATR logic to make successfully-retried test not affect
suite-level-or-above status
- Tweak to telemetry to add `is_retry` tag to `test`-level
`event_finished` metric

Finally, no release note is added as the feature is still unreleased.

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)