fix(tracing): ddtrace-run caused a traceback on keyboard interrupt (#18118)
## Description

<!-- Provide an overview of the change and motivation for the change -->

When someone does a keyboard interrupt with asyncio and dd-trace-py, we throw a traceback. The fix is not wrapping the default SIGINT handler. Regression tests have also been added to make sure we aren't causing issues. Note: that DSM will be pinged on this because I applied the fix on their side to have more consistent behavior.

This is for APMS-19516.

Example from this commit: 16843bd14bf16aa18183298fe69236a541e2de55

**core/ddtracerun 2/3** - https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/1686958431


>FAILED tests/commands/test_runner.py::test_ddtrace_run_asyncio_sigint[py3.10] - AssertionError: STDERR: Expected [b''] got [b'Traceback (most recent call last):\n  File "tests/commands/test_runner.py", line 564, in <module>\n    asyncio.run(main())\n  File "/home/bits/.pyenv/versions/3.10.19/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/home/bits/.pyenv/versions/3.10.19/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/home/bits/.pyenv/versions/3.10.19/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/home/bits/.pyenv/versions/3.10.19/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once\n    handle._run()\n  File "/home/bits/.pyenv/versions/3.10.19/lib/python3.10/asyncio/events.py", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/utils/signals.py", line 47, in wrap_signals\n    old_signal(*args, **kwargs)\nKeyboardInterrupt\n']

**core/ddtracerun 3/3** - https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/1686961383
> FAILED tests/commands/test_runner.py::test_ddtrace_run_asyncio_sigint[py3.11] - AssertionError: STDERR: Expected [b''] got [b'Traceback (most recent call last):\n  File "tests/commands/test_runner.py", line 564, in <module>\n    asyncio.run(main())\n  File "/home/bits/.pyenv/versions/3.11.14/lib/python3.11/asyncio/runners.py", line 190, in run\n    return runner.run(main)\n           ^^^^^^^^^^^^^^^^\n  File "/home/bits/.pyenv/versions/3.11.14/lib/python3.11/asyncio/runners.py", line 118, in run\n    return self._loop.run_until_complete(task)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/bits/.pyenv/versions/3.11.14/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete\n    self.run_forever()\n  File "/home/bits/.pyenv/versions/3.11.14/lib/python3.11/asyncio/base_events.py", line 608, in run_forever\n    self._run_once()\n  File "/home/bits/.pyenv/versions/3.11.14/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once\n    handle._run()\n  File "/home/bits/.pyenv/versions/3.11.14/lib/python3.11/asyncio/events.py", line 84, in _run\n    self._context.run(self._callback, *self._args)\n  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/utils/signals.py", line 47, in wrap_signals\n    old_signal(*args, **kwargs)\nKeyboardInterrupt\n']


Even the datastreams one would fail in this condition:

**contrib/datastreams 1/6** https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/1687110513
>       assert b"wrap_signals" not in err
E       assert b'wrap_signals' not in b'Traceback (most recent call last):\n  File "/tmp/pytest-of-bits/pytest-0/test_processor_flushes_on_sigi0/ddtrace_sub...-py/ddtrace/internal/utils/signals.py", line 47, in wrap_signals\n    old_signal(*args, **kwargs)\nKeyboardInterrupt\n'

**contrib/datastreams 2/6** https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/1687111190
>         assert "Fake flush called" in out.decode()
>       assert b"wrap_signals" not in err
E       assert b'wrap_signals' not in b'Traceback (most recent call last):\n  File "/tmp/pytest-of-bits/pytest-0/test_processor_flushes_on_sigi0/ddtrace_sub...-py/ddtrace/internal/utils/signals.py", line 47, in wrap_signals\n    old_signal(*args, **kwargs)\nKeyboardInterrupt\n'
tests/datastreams/test_processor.py:304: AssertionError
=============================== warnings summary ===============================
.riot/venv_py31212_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis6451_msgpack_pytest-randomly/lib/python3.12/site-packages/_pytest/config/__init__.py:1441
  /go/src/github.com/DataDog/apm-reliability/dd-trace-py/.riot/venv_py31212_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis6451_msgpack_pytest-randomly/lib/python3.12/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: asyncio_mode

## Testing

<!-- Describe your testing strategy or note what tests are included -->

1. Added regression tests to catch this behavior, see fa690f57efb34ac037ac06e80283dabe12bf8cd5
2. Then fixed them with a commit

## Risks

<!-- Note any risks associated with this change, or "None" if no risks -->

## Additional Notes

<!-- Any other information that would be helpful for reviewers -->


Co-authored-by: quinna-h <quinna.halim@datadoghq.com>