fix(llmobs): api_key can be Callable
**Problem**

Since openai 1.106.0, `api_key` can be callable or awaitable callable
for async client not only `str`.

Currently if callable `api_key` is passed, `TypeError` is raised.

```
TypeError: 'function' object is not subscriptable
```

**Solution**

Check if `api_key` is `str` or not and only format it if it is `str`.