chore(build, crashtracker): build w/ debug symbols (#14286)
Build all native extensions with debug symbols by default 
- `Cython.Distutils.Extension` and `setuptools.Extensions`: they inherit
`CFLAGS` from Python 's sysconfig, (`python -m sysconfig | grep
CFLAGS`), which would show `CFLAGS = "-fno-strict-overflow
-Wsign-compare -DNDEBUG -g -O3 -Wall"`. So they're built with debug
symbols always.
- `setuptools_rust.Extension`: We only have one Rust native extension in
`src/native`. This PR explicitly sets `debug ="line-tables-only"`.
- Our own `CMakeExtension`: Use CMake's `RelWithDebInfo` build type. By
default this would change optimization flag for Extensions built with
cmake, but only one is affected.


Extension | Release -O flag | RelWithDebInfo -O flag
-- | -- | --
ddtrace.internal.datadog.profiling.ddup._ddup | -Os as defined in
[AnalysisFunc.cmake](https://github.com/DataDog/dd-trace-py/blob/4ed3d21d4efd662c640720fe0ddf88088026e1a6/ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake#L11)
| -Os as defined in
[AnalysisFunc.cmake](https://github.com/DataDog/dd-trace-py/blob/4ed3d21d4efd662c640720fe0ddf88088026e1a6/ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake#L26)
ddtrace.internal.datadog.profiling.stack_v2._stack_v2 | -Os, same as
above | -Os, same as above
ddtrace.appsec._iast._taint_tracking._native | Not explicitly
overridden,probably -O3 | Not explicitly overridden,probably -O2

For both Linux and macOS, we emit debug symbols and then strip them from
the shared libraries.

This step is done before auditing/delocating wheel in the build GH
action. And the build GH action will also upload zipped debug symbols
for Linux and macOS as artifacts. The idea behind this is that external
developers could also download these and use if they wish. For our
internal crashtracker use, we'd need to upload them to our symbols
backend, and that will be done in a follow up PR. We'd like to upload
debug symbols for all future releases and release candidates by default.
For other builds, we'd have a manual trigger job.

When there's no debug symbols found from any of the .so/.dylib files,
except for those set to be ignored (e.g. libddwaf, which already is
stripped of debug symbols), the build GH actions will fail and tell you
which one doesn't have debug symbols.

See
https://github.com/DataDog/dd-trace-py/actions/runs/17137131985/job/48615775619?pr=14389
```
  ERROR: Failed to generate debug symbols for the following libraries:
    - ddtrace/appsec/_iast/_stacktrace.cpython-38-aarch64-linux-gnu.so
    - ddtrace/appsec/_iast/_ast/iastpatch.cpython-38-aarch64-linux-gnu.so
    - ddtrace/appsec/_iast/_taint_tracking/_native.cpython-38-aarch64-linux-gnu.so
...
  This indicates that these binaries were built without debug symbols (-g flag) or they were already stripped
  ERROR: Failed to extract debug symbols from wheel
```

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)