fix(flask): fix crashes with flask-like frameworks [backport 2.10] (#9755)
Backport 558c7c6c5eba938bf221d2a21c2a91437ada6fd0 from #9555 to 2.10.

## What does this PR do
Adds `provide_automatic_options` as an extra named argument to
`patched_add_url_rule`. Previously, when using a framework like
[`flask-openapi3`](https://pypi.org/project/flask-openapi3/), and
running the Hello World example linked using `ddtrace-run`, users would
see the following:

```
File "/Users/sam.brenner/Development/ml-obs/sandboxes/support/app.py", line 18, in <module>
    def get_book(query: BookQuery):
  File "/Users/sam.brenner/Development/ml-obs/sandboxes/support/.venv/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 182, in decorator
    self._add_url_rule(rule, view_func=view_func, **options)
  File "/Users/sam.brenner/Development/ml-obs/sandboxes/support/.venv/lib/python3.10/site-packages/flask_openapi3/openapi.py", line 411, in _add_url_rule
    self.add_url_rule(rule, endpoint, view_func, provide_automatic_options, **options)
  File "/Users/sam.brenner/Development/ml-obs/sandboxes/support/.venv/lib/python3.10/site-packages/ddtrace/contrib/flask/patch.py", line 433, in patched_add_url_rule
    return _wrap(*args, **kwargs)
TypeError: patched_add_url_rule.<locals>._wrap() takes from 1 to 3 positional arguments but 4 were given
```

After this change, this error is no longer present.

This is because `flask-openapi3` passes in `provide_automatic_options`
as an unnamed argument as the fourth positional argument, but is read on
Flask as a keyword arg.

## Testing

Added a regression test that instruments a barebones `flask-openapi3`
app, and runs Datadog instrumentation on it, asserting no errors.
Additionally, this change was verified manually in a running app, for
both instrumentation and execution.

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included
in the PR
- [x] Risks are described (performance impact, potential for breakage,
maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified
`@DataDog/apm-tees`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications
of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

Co-authored-by: Sam Brenner <106700075+sabrenner@users.noreply.github.com>