test(profiling): unflake a flaky test (#15746)
## Description

This is an attempt at making some of our tests non-flaky by flushing any
pre-existing state from `ddup`.

We are currently seeing some test failures on `main` with messages like 

```
builtins.AssertionError: Expected 877072757433302936 got 12345 for label span id
```

My theory is that this `12345` is the mock Span ID used in this test
that is leaking:


https://github.com/DataDog/dd-trace-py/blob/3841a702dbe647ace2da6840eaff398ab0376329/tests/profiling/exporter/test_ddup.py#L103-L106

I fixed this by:
1. Uploading any pre-existing Samples, we should be able to "focus" on
what we are actually producing in the test.
2. Additionally, updating the "leaky test" to push its data, which
should limit (hopefully completely mitigate) its blast radius on other
tests.
3. Unfortunately, this still wasn't enough (but I think it's still worth
keeping – because it limits the impact "leaks" can have on other tests),
so I also had to update the test logic to exclude any Samples that
weren't from `test_stack.py` (since we know for sure we aren't
interested in them).

These three fixes make the test now non-flaky.

The PR also makes the necessary changes in `pprof_utils` to make it
possible to implement the fixes.

[_See test runs in
Datadog_](https://app.datadoghq.com/ci/test/runs?query=test_level%3Atest%20%40ci.pipeline.name%3ADataDog%2Fapm-reliability%2Fdd-trace-py%20%40git.branch%3Akowalski%2Ftest-profiling-unflake-a-flaky-test%20status%3Aerror%20%40test.name%3A%2ATEMP%2A&agg_m=count&agg_m_source=base&agg_q=%40test.name&agg_q_source=base&agg_t=count&fromUser=true&top_n=10&top_o=top&viz=timeseries&x_missing=true&start=1766415411049&end=1766419011049&paused=false)