fix(sampling): fix agent sampling when tracer.configure is used (#13527)
When `tracer.configure` is called with a trace_processor, it causes the
writer to lose access to the response callback that processes sampling
rates because it triggers a writer `recreate` so there is no way it can
process the Trace Agent rates.

[We can see the test failure
here:](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/958533898)

```
=========================== short test summary info ============================
FAILED tests/integration/test_priority_sampling.py::test_sampling_rate_honored_tracer_configure{'DD_TRACE_API_VERSION': 'v0.5'} - AssertionError: Expected status 0, got 1.
=== Captured STDOUT ===
=== End of captured STDOUT ===
=== Captured STDERR ===
Traceback (most recent call last):
  File "tests/integration/test_priority_sampling.py", line 150, in <module>
    assert t._span_aggregator.writer._response_cb is not None
AssertionError
=== End of captured STDERR ===
FAILED tests/integration/test_priority_sampling.py::test_sampling_rate_honored_tracer_configure{'DD_TRACE_API_VERSION': 'v0.4'} - AssertionError: Expected status 0, got 1.
=== Captured STDOUT ===
=== End of captured STDOUT ===
=== Captured STDERR ===
Traceback (most recent call last):
  File "tests/integration/test_priority_sampling.py", line 150, in <module>
    assert t._span_aggregator.writer._response_cb is not None
AssertionError
```

Requires @emmettbutler 's
https://github.com/DataDog/dd-trace-py/pull/13512 to be merged in so the
tests actually run. Also shoutouts to @emmettbutler for showing me how
to run this! :)

Fixes APMS-15614


## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

---------

Co-authored-by: Emmett Butler <emmett.butler321@gmail.com>
Co-authored-by: Emmett Butler <723615+emmettbutler@users.noreply.github.com>