fix(pylibmc): support client initialization using servers [backport 2.21] (#12786)
Backport e08d99c22a4237cc3d04e0a863e5b8a889646220 from #12721 to 2.21.

Currently calling `Client(servers=[url])` throws an error as seen with
the new test:

[Example CI
error](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/847335230)
```
FAILED tests/contrib/pylibmc/test.py::TestPylibmcPatch::test_client_with_servers_option - TypeError: __init__() got multiple values for argument 'servers'
FAILED tests/contrib/pylibmc/test.py::TestPylibmcPatch::test_client_with_servers_option - TypeError: __init__() got multiple values for argument 'servers'
FAILED tests/contrib/pylibmc/test.py::TestPylibmcPatch::test_client_with_servers_option - TypeError: __init__() got multiple values for argument 'servers'
``` 

This is a bug in our integration logic because you can declare Clients
with and without the `servers` portion:
https://sendapatch.se/projects/pylibmc/reference.html .

**Why did this bug occur?**

When you call `pylibmc.Client(servers=[url])`, by the time it hits our
patch code, `**kwargs` already stores `servers`. Then when this gets
passed into the Client init, it sees two "servers"
https://github.com/lericson/pylibmc/blob/1183e48eb86adf0c23c5164bfe2c2a4058234640/src/pylibmc/client.py#L126,
hence the complaint about the multiple server arguments.

A quick fix is to check if the kwargs contains servers and set up the
client without duplicating it.



Fixes APMS-15146

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

---------

Co-authored-by: wantsui <wan.tsui@datadoghq.com>