chore(ci_visibility): fix CI Visibility errors in unittest test suite (#13445)
Currently our unittest test suite throws a lot of errors of this type:
```
Uncaught exception occurred while calling is_quarantined_test
Traceback (most recent call last):
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/ext/test_visibility/_utils.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/internal/test_visibility/api.py", line 193, in is_quarantined_test
    core.dispatch_with_results("test_visibility.test.is_quarantined", (item_id,)).is_quarantined.value
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/internal/core/event_hub.py", line 134, in dispatch_with_results
    results[name] = EventResult(ResultType.RESULT_OK, hook(*args))
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/internal/ci_visibility/recorder.py", line 1019, in wrapper
    return func(*args, **kwargs)
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/internal/ci_visibility/recorder.py", line 1311, in _on_is_quarantined_test
    return CIVisibility.get_test_by_id(test_id).is_quarantined()
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/internal/ci_visibility/recorder.py", line 784, in get_test_by_id
    return cls.get_suite_by_id(test_id.parent_id).get_child_by_id(test_id)
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/internal/ci_visibility/recorder.py", line 776, in get_suite_by_id
    return cls.get_module_by_id(suite_id.parent_id).get_child_by_id(suite_id)
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/internal/ci_visibility/recorder.py", line 768, in get_module_by_id
    return cls.get_session().get_child_by_id(module_id)
  File "/home/vitor.dearaujo/dd/dd-trace-py/ddtrace/internal/ci_visibility/recorder.py", line 759, in get_session
    raise CIVisibilityError(error_msg)
ddtrace.internal.ci_visibility.errors.CIVisibilityError: No session exists
No session exists
```

This happens because the tests enable CI Visibility, but this has the
consequence of enabling it also for the pytest session that is running
the tests. This PR changes the tests to disable it again when each test
finishes.

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)