fix(asyncpg): fix _TracedConnection error when using the connect option in create_pool (#14436)
**asyncpg 0.30.0** introduced a custom "connect" option when using
**create_pool**:
https://github.com/MagicStack/asyncpg/commit/3ee19baaba3971f8f21d2190e443b1e5f25a9052
.

As seen in gitlab:
https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/1102535027,
when this connect option is used, we get this error message:

> FAILED tests/contrib/asyncpg/test_asyncpg.py::test_pool_custom_connect
- asyncpg.exceptions._base.InterfaceError: expected pool connect
callback to return an instance of 'asyncpg.connection.Connection', got
'ddtrace.contrib.internal.asyncpg.patch._TracedConnection'

The root cause is that the asyncpg code does a check for connection
pools and expects it get a connect type of
`asyncpg.connection.Connection` but our tracer currently wraps around it
and returns a `_TracedConnection`:
https://github.com/MagicStack/asyncpg/blob/5b14653e0b447d956aa01ec658562138e19f0293/asyncpg/pool.py#L553

I added two tests since I couldn't find any create_pool tests:
- `test_pool_custom_connect` -> To test that we don't crash when the
custom connect option is used, and based on the snapshots it creates 1
`postgres.connect` span for every connect inside the pool. This test
should only run in 0.30.0+ since that's when the setting was introduced.
- `test_pool_without_custom_connect` -> To test that regardless of
whether someone uses the connect option or not, we should not be
throwing any errors. This doesn't create any `postgres.connect` spans.

Note: This is a second attempt at
https://github.com/DataDog/dd-trace-py/pull/13432/.

- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

- [x] Reviewer has checked that all the criteria below are met
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

(cherry picked from commit 3c576dc7d8e7308a54794d8c7522acc3f574d930)