fix(openai): fix typing import error for python 3.7 [backport #6219 to 1.14] (#6234)
`openai` integration doesn't work for me because of the issue with the
missing `TypedDict` type in Python 3.7. I'm receiving the following
error `ImportError: cannot import name 'TypedDict' from 'typing'`

I was able to reproduce it by adding  Python 3.7 to the test suite:
```
==================================== ERRORS ====================================
_____________ ERROR collecting tests/contrib/openai/test_logger.py _____________
ImportError while importing test module '/root/project/tests/contrib/openai/test_logger.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.pyenv/versions/3.7.16/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ddtrace/internal/module.py:220: in _exec_module
    self.loader.exec_module(module)
tests/contrib/openai/test_logger.py:8: in <module>
    from ddtrace.internal.log_writer import V2LogWriter
ddtrace/internal/module.py:220: in _exec_module
    self.loader.exec_module(module)
ddtrace/internal/log_writer.py:4: in <module>
    from typing import TypedDict
E   ImportError: cannot import name 'TypedDict' from 'typing' (/root/.pyenv/versions/3.7.16/lib/python3.7/typing.py)
```
`TypedDict` was added to typing in Python 3.8, so we can use it from
`typing_extensions` module for <3.8
Updated the test suite to be able to test with Python 3.7 as a minimum
supported version.

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included
in the PR.
- [x] Risk is outlined (performance impact, potential for breakage,
maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
are followed. If no release note is required, add label
`changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if
[applicable](../docs/contributing.rst#release-branch-maintenance))

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](../docs/contributing.rst#release-branch-maintenance)

Co-authored-by: Andrii Sherepa <asherepa@gmail.com>