chore: release script make create_pull all kwargs, better file adding for changelog (#8877)
When I used release script for 2.8 release:
errored out on this step:
```
Traceback (most recent call last):
  File "/Users/zach.groves/projects/dd-trace-py/scripts/release.py", line 489, in <module>
    create_changelog_pull_request(dd_repo, name, rn)
  File "/Users/zach.groves/projects/dd-trace-py/scripts/release.py", line 276, in create_changelog_pull_request
    commit_and_push(dd_repo, f"release.script/changelog-update-{name}", name)
  File "/Users/zach.groves/projects/dd-trace-py/scripts/release.py", line 269, in commit_and_push
    dd_repo.create_pull(DEFAULT_BRANCH, branch_name, title=f"chore: {pr_body}", body=f"- [x] {pr_body}", draft=False)
  File "/Users/zach.groves/projects/dd-trace-py/scripts/venv/lib/python3.9/site-packages/github/Repository.py", line 1399, in create_pull
    return self.__create_pull_1(*args, **kwds)
TypeError: __create_pull_1() got multiple values for argument 'title' 
```

I'm pretty sure this was due to a method signature change:
https://github.com/PyGithub/PyGithub/releases/tag/v2.1.0.post0


It also added other uncommitted files like .DS_Store. So I instead have
it just add the changelog file, since that's the only one that should be
different.

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included
in the PR
- [x] Risks are described (performance impact, potential for breakage,
maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified
`@DataDog/apm-tees`.

## Reviewer Checklist

- [ ] Title is accurate
- [ ] All changes are related to the pull request's stated goal
- [ ] Description motivates each change
- [ ] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- [ ] Testing strategy adequately addresses listed risks
- [ ] Change is maintainable (easy to change, telemetry, documentation)
- [ ] Release note makes sense to a user of the library
- [ ] Author has acknowledged and discussed the performance implications
of this PR as reported in the benchmarks PR comment
- [ ] Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

Co-authored-by: Brett Langdon <brett.langdon@datadoghq.com>