fix(llmobs): experiment evaluators arg has Sequence type (#16207)
## Description

On https://github.com/DataDog/dd-source/pull/341287, we ran into some
unexpected trouble after a recent change in ddtrace where the
`evaluators` arg of LLMObs.experiment changed from
```
        evaluators: List[Callable[[DatasetRecordInputType, JSONType, JSONType], JSONType]],
```
to
```
        evaluators: List[Callable[[DatasetRecordInputType, JSONType, JSONType], Union[JSONType, EvaluatorResult]]],
```
We encountered type checker errors in client code that passed a list of
Callable's where either the argument types were wider or the return type
was narrower, which was surprising. It turned out this is a well-known
issue with using mutable container types, which are invariant:
https://mypy.readthedocs.io/en/stable/common_issues.html#variance The
solution is to use a covariant type, Sequence.


## Testing

1. Copy this script under dd-trace-py/scripts:
https://github.com/DataDog/llm-obs/blob/test-type-check/demos/experiment_eval_metric/experiment_eval_metric.py#L61
2. Run `mypy scripts/experiment_eval_metric.py`
3. Observe similar type check error as what @emmettbutler encountered in
https://github.com/DataDog/dd-source/pull/341287:
```
scripts/experiment_eval_metric.py:68: error: Argument "evaluators" to "experiment" of "LLMObs" has incompatible type "list[Callable[[dict[str, str | int | float | bool | list[JSONType] | dict[str, JSONType]], JSONType, JSONType], JSONType]]"; expected "list[Callable[[dict[str, str | int | float | bool | list[JSONType] | dict[str, JSONType]], JSONType, JSONType], str | int | float | bool | list[JSONType] | dict[str, JSONType] | EvaluatorResult | None]]"  [arg-type]
scripts/experiment_eval_metric.py:68: note: "list" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
scripts/experiment_eval_metric.py:68: note: Consider using "Sequence" instead, which is covariant
```
4. Change type hint of `evaluators` arg to `Sequence[...]`
5. Re-run mypy, observe error is gone.

## Risks

None, users should not need to update anything.

---------

Co-authored-by: Yun Kim <35776586+Yun-Kim@users.noreply.github.com>