fix(asm): remote config test (#16125)
## Description

Update test_remote_configuration_1_click to allow multiple payloads
instead of requiring an exact match.

## Testing

Resolves the following test failures
([link](https://app.datadoghq.com/ci/test/runs?query=test_level%3Atest%20%40git.branch%3Amain%20%40test.status%3Afail%20%40test.codeowners%3A%22%40DataDog%2Fremote-config%22%20%40git.repository.name%3ADataDog%2A%2Fdd-trace-py%20%40test.full_name%3A%22tests.internal.remoteconfig.test_remoteconfig.py.test_remote_configuration_1_click%5Bpy3.11%5D%22&agg_m=count&agg_m_source=base&agg_t=count&fromUser=true&index=citest&start=1768837537995&end=1769096737995&paused=true)):

```
builtins.AssertionError: assert [Payload(meta...piration'}]})] == [Payload(meta...piration'}]})]
  
  Left contains one more item: Payload(metadata=ConfigMetadata(id='asm_features_activation', product_name='ASM_FEATURES', sha256_hash='b50fee2d49f343...27.0.0.0'}, {'expiration': 1662804872, 'value': '52.80.198.1'}], 'id': 'blocking_ips', 'type': 'ip_with_expiration'}]})
  
  Full diff:
    [
        Payload(
            metadata=ConfigMetadata(
                         id='asm_features_activation',
                         product_name='ASM_FEATURES',
                         sha256_hash='b50fee2d49f34364126ecbba696c4a5cb23fa0eb76169e5ed3139222e2bdae04',
                         length=24,
                         tuf_version=0,
                         apply_state=2,
                         apply_error=None,
                     ),
            path='datadog/2/ASM_FEATURES/asm_features_activation/config',
            content={
                        'rules_data': [
                            {
                                'data': [
                                    {
                                        'expiration': 1662804872,
                                        'value': '127.0.0.0',
                                    },
                                    {
                                        'expiration': 1662804872,
                                        'value': '52.80.198.1',
                                    },
                                ],
                                'id': 'blocking_ips',
                                'type': 'ip_with_expiration',
                            },
                        ],
                    },
        ),
  +     Payload(
  +         metadata=ConfigMetadata(
  +                      id='asm_features_activation',
  +                      product_name='ASM_FEATURES',
  +                      sha256_hash='b50fee2d49f34364126ecbba696c4a5cb23fa0eb76169e5ed3139222e2bdae04',
  +                      length=24,
  +                      tuf_version=0,
  +                      apply_state=2,
  +                      apply_error=None,
  +                  ),
  +         path='datadog/2/ASM_FEATURES/asm_features_activation/config',
  +         content={
  +                     'rules_data': [
  +                         {
  +                             'data': [
  +                                 {
  +                                     'expiration': 1662804872,
  +                                     'value': '127.0.0.0',
  +                                 },
  +                                 {
  +                                     'expiration': 1662804872,
  +                                     'value': '52.80.198.1',
  +                                 },
  +                             ],
  +                             'id': 'blocking_ips',
  +                             'type': 'ip_with_expiration',
  +                         },
  +                     ],
  +                 },
  +     ),
    ]
```


## Risks

<!-- Note any risks associated with this change, or "None" if no risks
-->

## Additional Notes

<!-- Any other information that would be helpful for reviewers -->