chore(iast): fix ci and replace add_log by add_error_log (#14682)
## Description

Fix IAST CI error introduced in this PR
https://github.com/DataDog/dd-trace-py/pull/14641

Refactor _set_iast_error_metric function. Replaced
`telemetry_writer.add_log` by `telemetry_writer.add_error_log`

Maybe we're hiding this error?

```
ERROR    ddtrace.internal.writer.writer:writer.py:444 failed to send, dropping 6 traces to intake at http://172.27.77.253:8126///evp_proxy/v2/api/v2/citestcycle after 5 retries
Traceback (most recent call last):
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/writer/writer.py", line 436, in _flush_single_payload
    self._send_payload_with_backoff(encoded, n_traces, client)
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/utils/retry.py", line 49, in retry_wrapped
    raise exception
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/utils/retry.py", line 40, in retry_wrapped
    result = f(*args, **kwargs)
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/writer/writer.py", line 309, in _send_payload
    response = self._put(payload, headers, client, no_trace=True)
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/ci_visibility/writer.py", line 192, in _put
    response = super()._put(data, headers, client, no_trace)
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/writer/writer.py", line 265, in _put
    self._conn.request(
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/http.py", line 37, in request
    return super().request(method, url, body=body, headers=_headers, encode_chunked=encode_chunked)
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/appsec/_common_module_patches.py", line 178, in wrapped_request
    return original_request_callable(*args, **kwargs)
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/appsec/_common_module_patches.py", line 178, in wrapped_request
    return original_request_callable(*args, **kwargs)
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/appsec/_common_module_patches.py", line 178, in wrapped_request
    return original_request_callable(*args, **kwargs)
  [Previous line repeated 491 more times]
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/appsec/_common_module_patches.py", line 158, in wrapped_request
    full_url = core.get_item("full_url")
  File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/ddtrace/internal/core/__init__.py", line 303, in get_item
    return _CURRENT_CONTEXT.get().get_item(data_key, default=default)
RecursionError: maximum recursion depth exceeded while calling a Python object
```