Pin protobuf to version 3 due to incompatibility with 4
Latest release of [protobuf](https://pypi.org/project/protobuf/) breaks profiling with

```
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 619, in <module>
    import ddtrace.profiling.auto  # noqa
  File "/usr/local/lib/python3.9/site-packages/ddtrace/profiling/__init__.py", line 5, in <module>
    from .profiler import Profiler  # noqa:F401
  File "/usr/local/lib/python3.9/site-packages/ddtrace/profiling/profiler.py", line 26, in <module>
    from ddtrace.profiling.exporter import file
  File "/usr/local/lib/python3.9/site-packages/ddtrace/profiling/exporter/file.py", line 6, in <module>
    from ddtrace.profiling.exporter import pprof
  File "ddtrace/profiling/exporter/pprof.pyx", line 33, in init ddtrace.profiling.exporter.pprof
  File "/usr/local/lib/python3.9/site-packages/ddtrace/profiling/exporter/pprof_pb2.py", line 38, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```