fix(internal): handle missing lib_config entry [backport 2.8] (#9026)
Backport b1dab58296355786c258bcd1b1c489a6f21f33aa from #9022 to 2.8.

This PR fixes an issue regarding the remote config module where a
payload missing the ``lib_config`` entry would crash the application due
to an unhandled ``KeyError`` exception.

```
KeyError: 'lib_config'
lib_config = config["lib_config"]
File "/usr/local/lib/python3.10/site-packages/ddtrace/settings/config.py", line 747, in _handle_remoteconfig
self._callback(data, test_tracer=test_tracer)
File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/remoteconfig/_subscribers.py", line 36, in _exec_callback
self._exec_callback(data, test_tracer=test_tracer)
File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/remoteconfig/_subscribers.py", line 41, in _get_data_from_connector_and_exec
self._get_data_from_connector_and_exec()
File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/remoteconfig/_subscribers.py", line 46, in periodic
Traceback (most recent call last):
```

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included
in the PR
- [x] Risks are described (performance impact, potential for breakage,
maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified
`@DataDog/apm-tees`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications
of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

Co-authored-by: Federico Mon <federico.mon@datadoghq.com>