fix(encoding): fix encoding errors when span start or duration exceeds LONG_MAX (#12368)
Possible cause behind
https://github.com/DataDog/dd-trace-py/issues/12240. If the span started
a very long time ago, the encoding fails with:

> > raise RuntimeError("failed to pack span: {!r}. Exception:
{}".format(span, e))
E RuntimeError: failed to pack span:
<Span(id=2850960614187153438,trace_id=137823137092894037702114325005943826011,parent_id=None,name=None)>.
Exception: Python int too large to convert to C long

Thanks to @emmettbutler for coming up with the fix.

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing
strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance
implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the
[release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

---------

Co-authored-by: Emmett Butler <emmett.butler321@gmail.com>
Co-authored-by: Emmett Butler <723615+emmettbutler@users.noreply.github.com>
Co-authored-by: Rachel Yang <rachel.yang@datadoghq.com>