fix(profiling/stack): lock _WeakSet in ThreadSpanLinks (#1469)
WeakSet are actually not thread safe since copy-ing them iterate over their
internal set. We need to lock those to make sure they are not mutated during
our iteration, otherwise you'd get RuntimeError:

  Exception in thread ddtrace.profiling.collector.stack:StackCollector:
  Traceback (most recent call last):
    File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
      self.run()
    File "/path/to/virtualenv/src/ddtrace/ddtrace/profiling/_periodic.py", line 48, in run
      self._target()
    File "/path/to/virtualenv/src/ddtrace/ddtrace/profiling/collector/__init__.py", line 21, in periodic
      for events in self.collect():
    File "ddtrace/profiling/collector/stack.pyx", line 408, in ddtrace.profiling.collector.stack.StackCollector.collect
    File "ddtrace/profiling/collector/stack.pyx", line 276, in ddtrace.profiling.collector.stack.stack_collect
    File "ddtrace/profiling/collector/stack.pyx", line 350, in ddtrace.profiling.collector.stack._ThreadSpanLinks.get_active_leaf_spans_from_thread_id
    File "/path/to/virtualenv/lib/python3.6/_weakrefset.py", line 60, in __iter__
      for itemref in self.data:
  RuntimeError: Set changed size during iteration

Fixes #1466