chore(events): fix potential circular import (#16894)
The events API benchmarks cannot be turned on because of a circular import. 

We are not seeing it in the code right now but it could happen eventually in other places than the benchmarks.

This PR decorates subscribers and trace_handlers to remove the potential future circular import.

Here is the stacktrace:
```python

2026-03-12T16:59:08.879338Z 01O Traceback (most recent call last):
2026-03-12T16:59:08.879357Z 01O   File "/app/benchmarks/scenario.py", line 7, in <module>
2026-03-12T16:59:08.879363Z 01O Traceback (most recent call last):
2026-03-12T16:59:08.879369Z 01O   File "/app/benchmarks/scenario.py", line 7, in <module>
2026-03-12T16:59:08.879372Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879376Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879446Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879461Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879468Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879475Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py", line 10, in <module>
2026-03-12T16:59:08.879478Z 01O     from ddtrace._trace.trace_handlers import _finish_span
2026-03-12T16:59:08.879482Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879487Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879489Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py", line 10, in <module>
2026-03-12T16:59:08.879492Z 01O Traceback (most recent call last):
2026-03-12T16:59:08.879497Z 01O   File "/app/benchmarks/scenario.py", line 7, in <module>
2026-03-12T16:59:08.879499Z 01O     from ddtrace._trace.trace_handlers import _finish_span
2026-03-12T16:59:08.879503Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879509Z 01O     Traceback (most recent call last):
2026-03-12T16:59:08.879511Z 01O self.loader.exec_module(module)
2026-03-12T16:59:08.879514Z 01O   File "/app/benchmarks/scenario.py", line 7, in <module>
2026-03-12T16:59:08.879519Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1527, in <module>
2026-03-12T16:59:08.879522Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879532Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879550Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879562Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1527, in <module>
2026-03-12T16:59:08.879567Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879573Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879576Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879582Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py", line 10, in <module>
2026-03-12T16:59:08.879588Z 01O     from ddtrace._trace.trace_handlers import _finish_span
2026-03-12T16:59:08.879591Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879594Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879605Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py", line 10, in <module>
2026-03-12T16:59:08.879608Z 01O     from ddtrace._trace.trace_handlers import _finish_span
2026-03-12T16:59:08.879612Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879617Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879619Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1527, in <module>
2026-03-12T16:59:08.879623Z 01O     listen()
2026-03-12T16:59:08.879634Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1337, in listen
2026-03-12T16:59:08.879638Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879642Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1527, in <module>
2026-03-12T16:59:08.879674Z 01O     listen()
2026-03-12T16:59:08.879676Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1337, in listen
2026-03-12T16:59:08.879679Z 01O     import ddtrace._trace.subscribers.http_client  # noqa: F401
2026-03-12T16:59:08.879684Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879687Z 01O     listen()
2026-03-12T16:59:08.879692Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1337, in listen
2026-03-12T16:59:08.879697Z 01O     import ddtrace._trace.subscribers.http_client  # noqa: F401
2026-03-12T16:59:08.879699Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879703Z 01O     listen()
2026-03-12T16:59:08.879707Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1337, in listen
2026-03-12T16:59:08.879710Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879713Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/http_client.py", line 5, in <module>
2026-03-12T16:59:08.879721Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879723Z 01O ImportError:     cannot import name 'TracingSubscriber' from partially initialized module 'ddtrace._trace.subscribers._base' (most likely due to a circular import) (/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py)self.loader.exec_module(module)
2026-03-12T16:59:08.879727Z 01O 
2026-03-12T16:59:08.879733Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/http_client.py", line 5, in <module>
2026-03-12T16:59:08.879736Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879739Z 01O ImportError: cannot import name 'TracingSubscriber' from partially initialized module 'ddtrace._trace.subscribers._base' (most likely due to a circular import) (/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py)
2026-03-12T16:59:08.879745Z 01O     import ddtrace._trace.subscribers.http_client  # noqa: F401
2026-03-12T16:59:08.879748Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879751Z 01O     import ddtrace._trace.subscribers.http_client  # noqa: F401
2026-03-12T16:59:08.879756Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879765Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879769Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/http_client.py", line 5, in <module>
2026-03-12T16:59:08.879781Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879791Z 01O ImportError:     cannot import name 'TracingSubscriber' from partially initialized module 'ddtrace._trace.subscribers._base' (most likely due to a circular import) (/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py)self.loader.exec_module(module)
2026-03-12T16:59:08.879796Z 01O 
2026-03-12T16:59:08.879802Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/http_client.py", line 5, in <module>
2026-03-12T16:59:08.879804Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879808Z 01O ImportError: cannot import name 'TracingSubscriber' from partially initialized module 'ddtrace._trace.subscribers._base' (most likely due to a circular import) (/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py)
2026-03-12T16:59:08.879826Z 01O Traceback (most recent call last):
2026-03-12T16:59:08.879829Z 01O   File "/app/benchmarks/scenario.py", line 7, in <module>
2026-03-12T16:59:08.879832Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879837Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879840Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879843Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py", line 10, in <module>
2026-03-12T16:59:08.879849Z 01O     from ddtrace._trace.trace_handlers import _finish_span
2026-03-12T16:59:08.879851Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879860Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879873Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1527, in <module>
2026-03-12T16:59:08.879877Z 01O     listen()
2026-03-12T16:59:08.879881Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/trace_handlers.py", line 1337, in listen
2026-03-12T16:59:08.879886Z 01O     import ddtrace._trace.subscribers.http_client  # noqa: F401
2026-03-12T16:59:08.879888Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/internal/module.py", line 313, in _exec_module
2026-03-12T16:59:08.879892Z 01O     self.loader.exec_module(module)
2026-03-12T16:59:08.879897Z 01O   File "/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/http_client.py", line 5, in <module>
2026-03-12T16:59:08.879900Z 01O     from ddtrace._trace.subscribers._base import TracingSubscriber
2026-03-12T16:59:08.879904Z 01O ImportError: cannot import name 'TracingSubscriber' from partially initialized module 'ddtrace._trace.subscribers._base' (most likely due to a circular import) (/app/benchmarks/.venv_baseline/lib/python3.9/site-packages/ddtrace/_trace/subscribers/_base.py)

```

Co-authored-by: louis.tricot <louis.tricot@datadoghq.com>