chore(tests): allow DD_API_KEY env var in tox tests (#4594)
## Description

Unblocks: https://github.com/DataDog/dd-trace-py/pull/4591

## Motivation

In tox if an environment variable is not defined in this [passenv](https://github.com/DataDog/dd-trace-py/blob/v1.6.1/tox.ini#L259) it will not be set. Currently the DD_API_KEY environment variable is filtered out when running profiler tests in tox. Unlike tox riot does not have a mechanism to ignore environment variables set in a host. This causes the following tests to pass in tox but fail in riot:

```
FAILED tests/profiling/test_profiler.py::test_url - AssertionError: assert '1...
FAILED tests/profiling/test_profiler.py::test_default_tracer_and_url - Assert...
FAILED tests/profiling/test_profiler.py::test_tracer_and_url - AssertionError...
FAILED tests/profiling/test_profiler.py::test_tracer_url - AssertionError: as...
FAILED tests/profiling/test_profiler.py::test_tracer_url_https - AssertionErr...
FAILED tests/profiling/test_profiler.py::test_tracer_url_uds_hostname - Asser...
FAILED tests/profiling/test_profiler.py::test_tracer_url_uds - AssertionError...
FAILED tests/profiling/test_profiler.py::test_env_no_api_key - AssertionError...
FAILED tests/profiling/test_profiler.py::test_env_endpoint_url - AssertionErr...
```

This PR:
- https://github.com/DataDog/dd-trace-py/pull/4594/commits/c23bd36ed3aead82bb905e4cd2d6087e6fd535f0 adds DD_API_KEY to the list of tox environment variables. This causes the tests listed above to [fail](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/24213/workflows/87524a06-bc90-4eec-874a-41ebe2850f26/jobs/1645305/parallel-runs/7)
- https://github.com/DataDog/dd-trace-py/pull/4594/commits/01f2395a172c5fbee8498c1426d9417af1160293 updates the profiling test to pass `os.getenv('DD_API_KEY')` to [_check_url((profiler_instance, url, api_key)](https://github.com/DataDog/dd-trace-py/blob/v1.6.1/tests/profiling/test_profiler.py#L209). Previously this value was expected to be None.


## Checklist
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.


## Reviewer Checklist
- [x] Title is accurate.
- [x] Description motivates each change.
- [x] No unnecessary changes were introduced in this PR.
- [x] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Tests provided or description of manual testing performed is included in the code or PR.
- [x] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [x] All relevant GitHub issues are correctly linked.
- [x] Backports are identified and tagged with Mergifyio.