fix(profiling): fix silent suppression of AssertionError exceptions in _ProfiledLock::_acquire (#15089)
https://datadoghq.atlassian.net/browse/PROF-12903

## Description
`_ProfiledLock::_maybe_update_self_name` raises `AssertionError` in two
places when `config.enable_asserts == True`.

However, they're being silently suppressed by the try/catch block in the
caller, `_ProfiledLock::_acquire`, method.

Current estimated impact is low, as it's only ever triggered for
development workflows, but still, worth making it right. This PR fixes
the bug by propagating `AssertionError`'s by the caller.

## Testing
Added two new tests: one for `AssertionError` and another for a
non-`AssertionError` exception.

**PROD**
_Test fails, since the `AssertionError` exception is not propagated_
```
$ ./scripts/ddtest riot -v run --pass-env d667cb4 -- -k test_assertion_error_suppressed_in_acquire
...
FAILED tests/profiling_v2/collector/test_threading.py::TestThreadingLockCollector::test_assertion_error_suppressed_in_acquire - Failed: DID NOT RAISE <class 'AssertionError'>
FAILED tests/profiling_v2/collector/test_threading.py::TestThreadingRLockCollector::test_assertion_error_suppressed_in_acquire - Failed: DID NOT RAISE <class 'AssertionError'>
```
_Highlighted code is for demonstration purposes only - not being merged_
<img width="703" height="735" alt="Screenshot 2025-10-30 at 10 36 28 AM"
src="https://github.com/user-attachments/assets/4c3d8066-3aa2-465e-8386-0f13a3de0cf6"
/>

**BRANCH**
_Test passes_
```
$ ./scripts/ddtest riot -v run --pass-env d667cb4 -- -k test_assertion_error_suppressed_in_acquire
...
tests/profiling_v2/collector/test_threading.py::TestThreadingLockCollector::test_assertion_error_suppressed_in_acquire PASSED
tests/profiling_v2/collector/test_threading.py::TestThreadingRLockCollector::test_assertion_error_suppressed_in_acquire PASSED
```
## Risks

none

[PROF-12903]:
https://datadoghq.atlassian.net/browse/PROF-12903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ